In [1]:
from qiskit import QuantumCircuit
from qiskit.quantum_info import DensityMatrix, Operator
import numpy as np
from qiskit.circuit.library import UGate, ZGate, HGate, SdgGate
from math import pi

In [2]:
np.vstack(
    [
        np.linspace(-np.pi, np.pi, 100),
        np.linspace(-4 * np.pi, 4 * np.pi, 100),
    ]
).T.shape

(100, 2)

In [16]:
HGate().to_matrix() @ SdgGate().to_matrix()

array([[0.70710678+0.j        , 0.        -0.70710678j],
       [0.70710678+0.j        , 0.        +0.70710678j]])

In [29]:
UGate(pi/2, 0, pi).to_matrix()

array([[ 0.70710678+0.00000000e+00j,  0.70710678-8.65956056e-17j],
       [ 0.70710678+0.00000000e+00j, -0.70710678+8.65956056e-17j]])

In [35]:
np.allclose(HGate().to_matrix(), UGate(pi/2, 0, pi).to_matrix())

True

In [36]:
np.allclose(ZGate().to_matrix(), UGate(0, 0, pi).to_matrix())

True

In [8]:
UGate(0, 0, 0).to_matrix()

array([[1.+0.j, 0.-0.j],
       [0.+0.j, 1.+0.j]])

In [3]:
ZGate()

Instruction(name='z', num_qubits=1, num_clbits=0, params=[])

In [4]:
to_bloch(0, 0, pi)

array([0., 0., 1.])

In [5]:
u.to_matrix()

array([[ 1.+0.0000000e+00j,  0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j, -1.+1.2246468e-16j]])

In [6]:
ZGate().to_matrix()

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [9]:
to_bloch(0, 0, 0)

array([0., 0., 1.])

In [10]:
t = [
    (0, 0, 1.0),
    (0, 0.1, 0.966228),
    (0, 0.2, 0.931476),
    (0, 0.3, 0.895553),
    (0, 0.4, 0.858199),
    (0, 0.5, 0.819036),
    (0, 0.6, 0.777485),
    (0, 0.7, 0.732574),
    (0, 0.8, 0.682405),
    (0, 0.9, 0.622076),
    (0, 1, 0.5),
    (0.1, 0, 0.966228),
    (0.1, 0.1, 0.936667),
    (0.1, 0.2, 0.906176),
    (0.1, 0.3, 0.874575),
    (0.1, 0.4, 0.841616),
    (0.1, 0.5, 0.80694),
    (0.1, 0.6, 0.77),
    (0.1, 0.7, 0.729872),
    (0.1, 0.8, 0.684755),
    (0.1, 0.9, 0.63),
    (0.1, 1, 0.516667),
    (0.2, 0, 0.931476),
    (0.2, 0.1, 0.906176),
    (0.2, 0.2, 0.88),
    (0.2, 0.3, 0.852777),
    (0.2, 0.4, 0.824273),
    (0.2, 0.5, 0.794152),
    (0.2, 0.6, 0.761895),
    (0.2, 0.7, 0.726633),
    (0.2, 0.8, 0.686667),
    (0.2, 0.9, 0.637614),
    (0.2, 1, 0.533333),
    (0.3, 0, 0.895553),
    (0.3, 0.1, 0.874575),
    (0.3, 0.2, 0.852777),
    (0.3, 0.3, 0.83),
    (0.3, 0.4, 0.806025),
    (0.3, 0.5, 0.780536),
    (0.3, 0.6, 0.75305),
    (0.3, 0.7, 0.722753),
    (0.3, 0.8, 0.688055),
    (0.3, 0.9, 0.644858),
    (0.3, 1, 0.55),
    (0.4, 0, 0.858199),
    (0.4, 0.1, 0.841616),
    (0.4, 0.2, 0.824273),
    (0.4, 0.3, 0.806025),
    (0.4, 0.4, 0.786667),
    (0.4, 0.5, 0.765908),
    (0.4, 0.6, 0.743299),
    (0.4, 0.7, 0.718088),
    (0.4, 0.8, 0.688803),
    (0.4, 0.9, 0.65165),
    (0.4, 1, 0.566667),
    (0.5, 0, 0.819036),
    (0.5, 0.1, 0.80694),
    (0.5, 0.2, 0.794152),
    (0.5, 0.3, 0.780536),
    (0.5, 0.4, 0.765908),
    (0.5, 0.5, 0.75),
    (0.5, 0.6, 0.732405),
    (0.5, 0.7, 0.712433),
    (0.5, 0.8, 0.688743),
    (0.5, 0.9, 0.657869),
    (0.5, 1, 0.583333),
    (0.6, 0, 0.777485),
    (0.6, 0.1, 0.77),
    (0.6, 0.2, 0.761895),
    (0.6, 0.3, 0.75305),
    (0.6, 0.4, 0.743299),
    (0.6, 0.5, 0.732405),
    (0.6, 0.6, 0.72),
    (0.6, 0.7, 0.70547),
    (0.6, 0.8, 0.687614),
    (0.6, 0.9, 0.663333),
    (0.6, 1, 0.6),
    (0.7, 0, 0.732574),
    (0.7, 0.1, 0.729872),
    (0.7, 0.2, 0.726633),
    (0.7, 0.3, 0.722753),
    (0.7, 0.4, 0.718088),
    (0.7, 0.5, 0.712433),
    (0.7, 0.6, 0.70547),
    (0.7, 0.7, 0.696667),
    (0.7, 0.8, 0.684983),
    (0.7, 0.9, 0.667735),
    (0.7, 1, 0.616667),
    (0.8, 0, 0.682405),
    (0.8, 0.1, 0.684755),
    (0.8, 0.2, 0.686667),
    (0.8, 0.3, 0.688055),
    (0.8, 0.4, 0.688803),
    (0.8, 0.5, 0.688743),
    (0.8, 0.6, 0.687614),
    (0.8, 0.7, 0.684983),
    (0.8, 0.8, 0.68),
    (0.8, 0.9, 0.670474),
    (0.8, 1, 0.633333),
    (0.9, 0, 0.622076),
    (0.9, 0.1, 0.63),
    (0.9, 0.2, 0.637614),
    (0.9, 0.3, 0.644858),
    (0.9, 0.4, 0.65165),
    (0.9, 0.5, 0.657869),
    (0.9, 0.6, 0.663333),
    (0.9, 0.7, 0.667735),
    (0.9, 0.8, 0.670474),
    (0.9, 0.9, 0.67),
    (0.9, 1, 0.65),
    (1, 0, 0.5),
    (1, 0.1, 0.516667),
    (1, 0.2, 0.533333),
    (1, 0.3, 0.55),
    (1, 0.4, 0.566667),
    (1, 0.5, 0.583333),
    (1, 0.6, 0.6),
    (1, 0.7, 0.616667),
    (1, 0.8, 0.633333),
    (1, 0.9, 0.65),
    (1, 1, 0.666667),
]